apiVersion: v1
kind: Service
metadata:
  name: app-nginx-blue
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: app-nginx-blue
