{{- define "base.configmap" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "base.name" . }}
data:
  index.html: |
    <html style="text-align:center"><body style="background-color:{{ .Values.appColor }};">
    <br><h1>Welcome, {{ .Values.community }} Community!</h1></br>
    <h2>This is {{ template "base.name" . }} Homepage.</h2> </br>
    <h3>Node-Name: $MY_NODE_NAME </br> Pod-IP: $MY_POD_IP </h3>
    </body></html>
{{- end -}}
