{{- define "base.service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "base.name" . }}
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: {{ template "base.name" . }}
{{- end -}}
