{{- define "base.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "base.name" . }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ template "base.name" . }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: {{ template "base.name" . }}
    spec:
      containers:
      - image: nginx:latest
        name: {{ template "base.name" . }}
        lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "envsubst < /tmp/index.html > /usr/share/nginx/html/index.html"]
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - mountPath: /tmp
          name: homepage-mount
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      volumes:
      - name: homepage-mount
        configMap:
          name: {{ template "base.name" . }}
{{- end -}}